name: Android CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Checkout xihan123/YukiHookAPI
#        uses: actions/checkout@v4
#        with:
#          submodules: 'recursive'
#          fetch-depth: 0
#          repository: xihan123/YukiHookAPI
#          path: xihan123/YukiHookAPI
#
#      - name: Build dependencies
#        working-directory: xihan123
#        run: |
#          cd YukiHookAPI
#          chmod +x gradlew
#          ./gradlew publishToMavenLocal

      - name: Build with Gradle
        run: |
          ./gradlew :app:aR

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: app/build/outputs
